PRETRAINED_EMBEDDING = "pre-trained",
ONE_HOT_EMBEDDING = "one-hot"
ATTRIBUTE_EMBEDDING = "attribute"
TUPLE_EMBEDDING = "tuple"
EMBEDDING_TYPES = [PRETRAINED_EMBEDDING, ONE_HOT_EMBEDDING,
                   ATTRIBUTE_EMBEDDING, TUPLE_EMBEDDING]
NUMERIC = "numeric"
CATEGORICAL = "categorical"
EMBEDDABLE = "embeddable_categorical"
DATA_TYPES = [NUMERIC, CATEGORICAL, EMBEDDABLE]
